services:
  # PostgreSQL with PostGIS for location data
  postgres:
    image: postgis/postgis:13-3.1
    container_name: aapat_postgres
    environment:
      POSTGRES_USER: aapat_user
      POSTGRES_PASSWORD: aapat_password
      POSTGRES_DB: aapat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - aapat_network

  # Redis for caching and real-time data
  redis:
    image: redis:7-alpine
    container_name: aapat_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aapat_network

  # Emergency Request Service
  emergency-service:
    build:
      context: ./services/emergency-service
      dockerfile: Dockerfile
    container_name: aapat_emergency_service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=aapat_user
      - DB_PASSWORD=aapat_password
      - DB_NAME=aapat_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DISPATCH_SERVICE_URL=http://dispatch-service:3003
      - COMMUNICATION_SERVICE_URL=http://communication-service:3006
      - PATIENT_SERVICE_URL=http://patient-service:3005
    depends_on:
      - postgres
      - redis
    networks:
      - aapat_network

  # Ambulance Management Service
  ambulance-service:
    build:
      context: ./services/ambulance-service
      dockerfile: Dockerfile
    container_name: aapat_ambulance_service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=aapat_user
      - DB_PASSWORD=aapat_password
      - DB_NAME=aapat_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - aapat_network

  # Dispatch Service
  dispatch-service:
    build:
      context: ./services/dispatch-service
      dockerfile: Dockerfile
    container_name: aapat_dispatch_service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=aapat_user
      - DB_PASSWORD=aapat_password
      - DB_NAME=aapat_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AMBULANCE_SERVICE_URL=http://ambulance-service:3002
      - EMERGENCY_SERVICE_URL=http://emergency-service:3001
      - HOSPITAL_SERVICE_URL=http://hospital-service:3004
    depends_on:
      - postgres
      - redis
      - emergency-service
      - ambulance-service
    networks:
      - aapat_network

  # Hospital Integration Service
  hospital-service:
    build:
      context: ./services/hospital-service
      dockerfile: Dockerfile
    container_name: aapat_hospital_service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=aapat_user
      - DB_PASSWORD=aapat_password
      - DB_NAME=aapat_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - aapat_network

  # Patient Management Service
  patient-service:
    build:
      context: ./services/patient-service
      dockerfile: Dockerfile
    container_name: aapat_patient_service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=aapat_user
      - DB_PASSWORD=aapat_password
      - DB_NAME=aapat_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=GFlAsYpaKyY5zyKqYi0j1LLAtPmaL2r+n/cnSus4Ob4=
    depends_on:
      - postgres
      - redis
    networks:
      - aapat_network

  # Communication Service
  communication-service:
    build:
      context: ./services/communication-service
      dockerfile: Dockerfile
    container_name: aapat_communication_service
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=aapat_user
      - DB_PASSWORD=aapat_password
      - DB_NAME=aapat_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TWILIO_ACCOUNT_SID=ACa4cc047c52d3f093275ff9144c4ec351
      - TWILIO_AUTH_TOKEN=fcc0e7431199c26382f30bc3a0ccda22
      - TWILIO_PHONE_NUMBER=+16674463150
      - FIREBASE_SERVICE_ACCOUNT_KEY=your-firebase-key
    depends_on:
      - postgres
      - redis
    networks:
      - aapat_network

  # Billing Service
  billing-service:
    build:
      context: ./services/billing-service
      dockerfile: Dockerfile
    container_name: aapat_billing_service
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=aapat_user
      - DB_PASSWORD=aapat_password
      - DB_NAME=aapat_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - STRIPE_SECRET_KEY=sk_test_your_stripe_key
      - RAZORPAY_KEY_ID=rzp_test_RFghxBO5zdCwbL
      - RAZORPAY_KEY_SECRET=c4kCtdCxSaNBZmJvcQWZL2LY
    depends_on:
      - postgres
      - redis
    networks:
      - aapat_network

  # Analytics Service
  analytics-service:
    build:
      context: ./services/analytics-service
      dockerfile: Dockerfile
    container_name: aapat_analytics_service
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=aapat_user
      - DB_PASSWORD=aapat_password
      - DB_NAME=aapat_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - aapat_network

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: aapat_api_gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - EMERGENCY_SERVICE_URL=http://emergency-service:3001
      - AMBULANCE_SERVICE_URL=http://ambulance-service:3002
      - DISPATCH_SERVICE_URL=http://dispatch-service:3003
      - HOSPITAL_SERVICE_URL=http://hospital-service:3004
      - PATIENT_SERVICE_URL=http://patient-service:3005
      - COMMUNICATION_SERVICE_URL=http://communication-service:3006
      - BILLING_SERVICE_URL=http://billing-service:3007
      - ANALYTICS_SERVICE_URL=http://analytics-service:3008
      - JWT_SECRET=GFlAsYpaKyY5zyKqYi0j1LLAtPmaL2r+n/cnSus4Ob4=
    depends_on:
      - emergency-service
      - ambulance-service
      - dispatch-service
      - hospital-service
      - patient-service
      - communication-service
      - billing-service
      - analytics-service
    networks:
      - aapat_network

volumes:
  postgres_data:
  redis_data:

networks:
  aapat_network:
    driver: bridge
